# Copyright (c) 2024 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: cfriedt
      url-base: https://github.com/cfriedt
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  # zephyr-keep-sorted-start re(^\s+\- name:)
  projects:
    - name: librpmi
      remote: cfriedt
      path: modules/lib/librpmi
      revision: e94e842eadc20e0269ae02d8d069de2604cd5f41
    - name: zephyr
      remote: zephyrproject-rtos
      # a stable-ish commit before v4.3.0-rc1
      revision: 3ced42c5e5272d15fa9bba1dd57614ee0fbc5de4
      import:
        name-allowlist:
          - cmsis_6
          - hal_stm32
          - mbedtls
          - mcuboot
          - nanopb
          - segger
  # zephyr-keep-sorted-stop

  group-filter:
    - +optional
